### ISSUE TITLE
Fluidify navigation 

### ISSUE THREAD

**Issue by adrienluitot** [rajeev29five/rajeev29five.github.io#5]
I think it would be better to remove the `target="_blank"` of the card(s), it's a bit annoying.
And maybe add a link on the default layout to be able to back to the index.

**Comment by rajeev29five** [comment]
The home page was supposed to have more cards that's why `target="_blank"` but I got caught up in some work. I never noticed that link to index page was missing thanks for pointing out, if you wanna work on it go ahead and make a PR.

**Comment by adrienluitot** [comment]
Yes but I think it's still better to open the page on the same window, we can easily go back to the main page using the back arrow of the navigator or with the future button :yum:.
Okay I'll make a PR ;)
